version: 1
groups:
  - annotation: ckanext-oidc-pkce
    options:
      - key: ckanext.cognito_oidc.base_url
        required: true
        description: URL of SSO application
        placeholder: https://12345.amazoncognito.com

      - key: ckanext.cognito_oidc.client_id
        required: true
        description: ClientID of SSO application
        placeholder: clientid

      - key: ckanext.cognito_oidc.auth_path
        default: /oauth2/authorize
        example: /authorize
        description: |
          Path to the authorization endpont inside SSO application

      - key: ckanext.cognito_oidc.token_path
        default: /oauth2/token
        example: /token
        description: Path to the token endpont inside SSO application

      - key: ckanext.cognito_oidc.userinfo_path
        default: /oauth2/userinfo
        example: /userinfo
        description: Path to the userinfo endpont inside SSO application

      - key: ckanext.cognito_oidc.redirect_path
        default: /user/login/cognito_oidc/callback
        example: /local/oidc/handler
        description: |
          Path to the authentication response handler inside CKAN application

      - key: ckanext.cognito_oidc.error_redirect
        default: null
        example: /user/register
        description: |
          URL to redirect user in case of failed login attempt.  When
          empty(default) redirects to `came_from` URL parameter if availabe or
          to CKAN login page otherwise.

      - key: ckanext.cognito_oidc.scope
        default: openid+profile+aws.cognito.signin.user.admin
        example: email
        description: |
          Scope of the authorization token. The plugin expects at least `sub`,
          `email` and `name` attributes.

      - key: ckanext.cognito_oidc.use_same_id
        type: bool
        default: false
        example: "true"
        description: |
          For newly created CKAN users use the same ID as one from SSO
          application

      - key: ckanext.cognito_oidc.munge_password
        type: bool
        default: false
        example: "true"
        description: |
          When connecting to an existing(non-sso) account, override user's
          password so that it becomes impossible to login using CKAN
          authentication system. Enable this flag if you want to force
          SSO-logins for all users that once used SSO-login.
